Adding Readme

diff --git a/git-init-repo b/git-init-repo
--- a/git-init-repo
+++ b/git-init-repo
@@ -5,10 +5,11 @@ PROJECTNAME="PreliminaryPudding"
 PROJECTTYPE="VisualStudio"
 REPONAME="${PWD##*/}"
 REMOTE="origin"
+HOST="devops"
 INIT=1
 
 usage() {
-    echo "Usage: `basename "$0"` [--name name] [--project project-name] [--instance instance] [--type type]"
+    echo "Usage: `basename "$0"` [--host github|devops] [--name name] [--project project-name] [--instance instance] [--type type]"
     exit 1
 }
 
@@ -41,6 +42,10 @@ do
         --no-init)
             INIT=0
         ;;
+        --host|-h)
+            HOST="$1"
+            shift
+        ;;
         *)
             echo "Unknown parameter: $key"
             usage
@@ -53,12 +58,24 @@ if [ -z "$REPONAME" ]; then
     usage
 fi
 
-echo -e "Creating Azure Devops repo \n Instance: $INSTANCE \n Project: $PROJECTNAME \n Repository name: $REPONAME"
-SSHURL=`vsts code repo create --instance "$INSTANCE" --project "$PROJECTNAME" --name "$REPONAME" --query "additionalProperties.sshUrl" | sed 's/"//g'`
-if [ $? != 0 ]; then
-    echo "Devops repo creation failed, aborting."
-    exit
+if [ $HOST = "devops" ]; then
+    echo -e "Creating Azure Devops repo \n Instance: $INSTANCE \n Project: $PROJECTNAME \n Repository name: $REPONAME"
+    SSHURL=`vsts code repo create --instance "$INSTANCE" --project "$PROJECTNAME" --name "$REPONAME" --query "additionalProperties.sshUrl" | sed 's/"//g'`
+    if [ $? != 0 ]; then
+        echo "Devops repo creation failed, aborting."
+        exit
+    fi
 fi
+
+if [ $HOST = "github" ]; then
+    echo -e "Creating GitHub repo $REPONAME"
+    SSHURL=`gh repo create $REPONAME -o tsv --query ssh_url`
+    if [ -z $SSHURL ]; then
+        echo "Github repo creation failed, aborting."
+        exit
+    fi
+fi
+
 echo "Initializing git"
 
 if [ $INIT = 1 ]; then
